[package]
name = "rdma"
version = "0.1.0"
authors = ["Qingming Qu <quqingming@gmail.com>"]
edition = "2021"

# [[bin]]
# name = "s"
# path = "examples/rdma_server.rs"

[dependencies]
rdmaffi = { path = "../rdma-sys", package = "rdma-sys", version = "0.1.0" }
libc = "0.2.94"
